---

- name: "Include riskms hosts"
  lineinfile: 
    dest: /etc/hosts
    line: '{{item.ip_addr}} {{ item.host_name }}'
    state: present
  become: yes
  with_items: "{{riskms_hosts}}"

- name: "Check computer's product model"
  set_fact:
    is_modern_probook: "{{ansible_facts['product_name'] == 'HP ProBook 440 G8 Notebook PC'}}"

- name: "Configure alsa service for soundcard if modern laptop"
  copy:
     dest: /etc/modprobe.d/alsa-base.conf
     content: |
        options snd-hda-intel dmic_detect=0
  when: is_modern_probook

- name: "Configure blacklist for soundcard if modern laptop"
  copy:
     dest: /etc/modprobe.d/blacklist.conf
     content: |
        blacklist snd_soc_skl
  when: is_modern_probook

