---

- name: "Include riskms hosts"
  lineinfile: 
    dest: /etc/hosts
    line: '{{item.ip_addr}} {{ item.host_name }}'
    state: present
  become: yes
  with_items: "{{riskms_hosts}}"

- name: "Check computer's product model"
  set_fact:
    is_modern_probook: "{{ansible_facts['product_name'] == 'HP ProBook 440 G8 Notebook PC'}}"

- name: "Install firmware sof signed"
  package:
     name: firmware-sof-signed
     state: present
  become: yes   
  when: is_modern_probook
  
- name: "set a random hostname"
  hostname:
     name: "{{ 999999999999999999995 | random | to_uuid }}"

