#!/bin/bash
### BEGIN INIT INFO
# Provides:       ad-connect
# Required-Start:    \$local_fs \$syslog
# Required-Stop:     \$local_fs \$syslog
# Default-Start:     5
# Default-Stop:      6
# Short-Description: starts ad-connect
# Description:       starts ad-connect using start-stop-daemon
### END INIT INFO
touch /root/flag.file
systemctl restart sssd
AD_USER=`cat /root/ad_user`
AD_DOMAIN=`cat /root/ad_domain`
cat /root/ad_cred| realm join -U $AD_USER $AD_DOMAIN
pam-auth-update --enable mkhomedir
wget https://raw.githubusercontent.com/daniel-alonso-sanchez/debian-ansible-preseed/ad/xsessionrc -O /etc/skel/.xsessionrc
sed -i 's|use_fully_qualified_names = True|use_fully_qualified_names = False|g' /etc/sssd/sssd.conf
sed -i 's|/home/%u@%d|/home/%u|g' /etc/sssd/sssd.conf
cat <<EOT >> /etc/sssd/sssd.conf
account_cache_expiration = 15

[pam]
offline_credentials_expiration = 15
reconnection_retries = 3
EOT
systemctl restart sssd


exit 0
