---
# tasks file for tools

- name: "fetching and installing"
  include: fetch_and_extract.yml tool={{item}}  
  with_items: "{{ tools }}"

- name: "installing slack"
  apt:
    deb: "{{item}}"
  become: yes
  with_items: "{{debs}}"
